<tmpl_if is_de>
Insgesamt <tmpl_var category_count> Systematikstellen, <tmpl_var total_folder_count> Mappen.

Nur grob geschätzt ein Fünftel des digitalisierten Bestandes des
Länder-/Sacharchivs bis 1949 ist in Mappen erschlossen und über diese
Systematik zugänglich. Viele kleine und große Länder wie Großbritannien,
China, Indien, Frankreich oder die USA fehlen ganz oder sind nur mit
einzelnen, aus der "Forschungsstelle für das Übersee-Deutschtum" übernommenen
Mappen vertreten.

Alles nicht aufbereitete Material ist unter [digitalisierte
Filme](/film/h1_sh.de.html) zugänglich, auch solches aus der [2. Verfilmung
(bis 1960)](/film/h2_sh.de.html) - aus urheberrechtlichen Gründen allerdings
leider nur im ZBW-Lesesaal. Die
[vollständige Sachsystematik](https://pm20.zbw.eu/report/pm20_result.de.html?jsonFile=vocab/subject_by_signature.de.json&main_title=Sachsystematik)
ist online verfügbar.
</tmpl_if>
<tmpl_if is_en>
In total <tmpl_var category_count> categories, <tmpl_var folder_count> folders.

Of the PM20 Länder-/Sacharchiv up to 1949, only a rough estimate of one-fifth
of the digitized holdings are indexed in folders and accessible via this
category system. Many small and large countries such as Great Britain,
China, India, France or the USA are missing at all or are only represented by a
few folders originating from the "Forschungsstelle für das Übersee-Deutschtum".

All unprocessed material is accessible under [digitized
films](/film/h1_sh.de.html) (in German), including material from the [second
filming (until 1960)](/film/h2_sh.de.html) - for copyright reasons, however,
unfortunately only in the ZBW reading room. The [complete subject category
system](https://pm20.zbw.eu/report/pm20_result.de.html?jsonFile=vocab/subject_by_signature.en.json&main_title=Subject+category+system)
is available online.
</tmpl_if>

