<a id="filmsections"><tmpl_if filmsection1_loop>

<tmpl_if is_de>
## Abschnitte von digitalisierten Mikrofilmen (1. Verfilmung 1908-1949)

Aus urheberrechtlichen Gründen nur im ZBW-Lesesaal zugänglich.
</tmpl_if is_de>
<tmpl_if is_en>
## Sections of digitized microfilms (1st filming 1908-1949)

For intellectual property law reasons accessible only from ZBW reading room.
</tmpl_if is_en>

<tmpl_include name="film_image_number.md.inc">

<tmpl_include name="sectiontable.md.inc">

</tmpl_if filmsection1_loop>

<tmpl_if filmsection2_loop>

<tmpl_if is_de>
## Abschnitte von digitalisierten Mikrofilmen (2. Verfilmung 1950-1960)

Aus urheberrechtlichen Gründen nur im ZBW-Lesesaal zugänglich.
</tmpl_if is_de>

<tmpl_if is_en>
## Sections of digitized microfilms (2nd filming 1950-1960)

For intellectual property law reasons accessible only from ZBW reading room.
</tmpl_if is_en>

<tmpl_include name="film_image_number.md.inc">

<tmpl_include name="film_image_number.md.inc">

</tmpl_if filmsection2_loop>

