<tmpl_if is_de>
Gesamtzahl der Mikrofilmaufnahmen: <tmpl_if total_number_of_images><tmpl_var total_number_of_images><tmpl_else>
unbekannt. Weiteres Material ist möglicherweise in der [Filmliste](<tmpl_var filmlist_link>) zu entdecken.</tmpl_if>
</tmpl_if is_de>
<tmpl_if is_en>
Total number of images: <tmpl_if total_number_of_images><tmpl_var total_number_of_images><tmpl_else>
unknown. Further material is possibly discoverable in the [film list](<tmpl_var filmlist_link>.</tmpl_if>
</tmpl_if is_en>
