<tmpl_if is_de>
Insgesamt <tmpl_var category_count> Systematikstellen, <tmpl_var
subject_total_folder_count> Sach-Mappen, <tmpl_var ware_total_folder_count>
Waren-Mappen<tmpl_if subject_total_image_count></tmpl_if><tmpl_if ware_total_image_count></tmpl_if>.


Nur grob geschätzt ein Fünftel des digitalisierten Bestandes des
Länder-/Sacharchivs bis 1949 ist in Mappen erschlossen und über diese
Systematik zugänglich. Die entsprechenden Länder und Regionen - z.B. der Nahe
Osten, Japan, die ehemaligen deutschen Kolonien oder Hamburg - sind unten mit
"komplett" gekennzeichnet. Viele kleine und große Länder wie Großbritannien,
China, Indien, Frankreich oder die USA fehlen jedoch ganz oder sind nur mit
einzelnen, aus der "Forschungsstelle für das Übersee-Deutschtum" übernommenen
Mappen vertreten.

Für das Warenarchiv ist grob geschätzt nur ein Achtel des digitalisierten
Bestandes erschlossen. Die Waren-Mappen für ein bestimmtes Land sind daher
stets unvollständig.

Alles nicht aufbereitete Material ist unter [digitalisierte
Filme](/film/h1_sh.de.html) zugänglich, auch solches aus der [2. Verfilmung
(bis 1960)](/film/h2_sh.de.html) - aus urheberrechtlichen Gründen allerdings
leider nur im ZBW-Lesesaal. Die
[vollständige Ländersystematik](https://pm20.zbw.eu/report/vocab/geo_by_signature.de.html)
ist online verfügbar.
</tmpl_if>

<tmpl_if is_en>
In total <tmpl_var category_count> categories, <tmpl_var
subject_total_folder_count> subject folders, <tmpl_var ware_total_folder_count>
ware folders.


Of the PM20 Länder-/Sacharchiv up to 1949, only a rough estimate of one-fifth
of the digitized holdings are indexed in folders and accessible via this
category system. The corresponding countries and regions - e.g. the Middle
East, Japan, the former German colonies or Hamburg - are marked "complete" in
the list below. However, many small and large countries such as Great Britain,
China, India, France or the USA are missing at all or are only represented by a
few folders originating from the "Forschungsstelle für das Übersee-Deutschtum".

For the Commodities/Wares archive, only about one-eighth of the digitized
material is accessible here. The wares folders for every given coutry are
therefore always incomplete.

All unprocessed material is accessible under [digitized
films](/film/h1_sh.de.html) (in German), including material from the [second
filming (until 1960)](/film/h2_sh.de.html) - for copyright reasons, however,
unfortunately only in the ZBW reading room. The [complete country category
system](https://pm20.zbw.eu/report/vocab/geo_by_signature.en.html)
is available online.
</tmpl_if>

