<tmpl_if is_de>
Insgesamt <tmpl_var category_count> Systematikstellen, <tmpl_var
geo_total_folder_count> Mappen (bis 1949) und <tmpl_var geo_total_image_count>
Aufnahmen auf digitalisierten Mikrofilmen.

Das Warenarchiv war primär nach Warenarten gegliedert, sekundär nach Ländern
(oder "Welt" für Übergreifendes). Bei umfangreicheren Warenmappen gab es
innerhalb der Mappe eine [systematische Aufteilung
(pdf)](https://pm20.zbw.eu/doc/hwwa/ware/warenarchiv_1908-1945_schemata.pdf),
die in den elektronischen Mappen nicht abgebildet ist.

Nur grob geschätzt ein Achtel des digitalisierten Bestandes des
Warenarchivs bis 1949 ist in Mappen erschlossen und global im Web zugänglich.
Viele kleine und große Warenarten wie Getreide, Kaffee, Kraftwagen oder Metalle
fehlen unter den Mappen und sind nur unter gewissen Einschränkungen auf
digitalisierten Mikrofilmen zugänglich.

Weiteres nicht aufbereitetes Material aus der [2. Verfilmung (bis
1960)](/film/h2_wa.de.html) ist aus urheberrechtlichen Gründen 
leider nur im ZBW-Lesesaal zugänglich. Die [vollständige
Warensystematik](https://pm20.zbw.eu/report/vocab/ware_by_signature.de.html)
ist online verfügbar.
</tmpl_if>
<tmpl_if is_en>
In total <tmpl_var category_count> categories, <tmpl_var
geo_total_folder_count> folders (until 1949) and <tmpl_var
geo_total_image_count> images on digitized microfilm.

The Commodities/Wares archive was organized primarily by type of ware,
seconadarily by country (or "World" for general aspects). Larger folders were
subdivided by a [category sytem (pdf, in
German)](https://pm20.zbw.eu/doc/hwwa/ware/warenarchiv_1908-1945_schemata.pdf),
which is not adressable in the electronic folder.

Of the PM20 Commodities/Wares archives up to 1949, only a rough estimate of
one-eighth of the digitized holdings are indexed in folders and accessible
here. Many small and large commodities/wares such as grain, coffee, motor
vehicle or metal are missing among the folders and are acceible only as
sections of digitized microfilm under certain restrictions.

Further unprocessed material from the [second filming (until
1960)](/film/h2_wa.de.html) is, for copyright reasons, accessible only in the
ZBW reading room. The [complete ware category
system](https://pm20.zbw.eu/report/vocab/ware_by_signature.en.html) is
available online.
</tmpl_if>

