<tmpl_if is_de>
Insgesamt <tmpl_var category_count> Systematikstellen, <tmpl_var
geo_total_folder_count> Mappen.

Das Warenarchiv war primär nach Warenarten gegliedert, sekundär nach Ländern
(oder "Welt" für Übergreifendes). Bei umfangreicheren Warenmappen gab es
innerhalb der Mappe eine [systematische Aufteilung
(pdf)](https://pm20.zbw.eu/doc/hwwa/ware/warenarchiv_1908-1945_schemata.pdf),
die in den elektronischen Mappen nicht abgebildet ist.

Nur grob geschätzt ein Achtel des digitalisierten Bestandes des
Warenarchivs bis 1949 ist in Mappen erschlossen und hier zugänglich. Viele
kleine und große Warenarten wie Getreide, Kaffee, Kraftwagen oder Metalle
fehlen hier.

Alles nicht aufbereitete Material ist unter [digitalisierte
Filme](/film/h1_wa.de.html) zugänglich, auch solches aus der [2. Verfilmung
(bis 1960)](/film/h2_wa.de.html) - aus urheberrechtlichen Gründen allerdings
leider nur im ZBW-Lesesaal. Die [vollständige
Warensystematik](https://pm20.zbw.eu/report/vocab/ware_by_signature.de.html)
ist online verfügbar.
</tmpl_if>
<tmpl_if is_en>
In total <tmpl_var category_count> categories, <tmpl_var
geo_total_folder_count> folders.

The Commodities/Wares archive was organized primarily by type of ware,
seconadarily by country (or "World" for general aspects). Larger folders were
subdivided by a [category sytem (pdf, in
German)](https://pm20.zbw.eu/doc/hwwa/ware/warenarchiv_1908-1945_schemata.pdf),
which is not adressable in the electronic folder.

Of the PM20 Länder-/Sacharchiv up to 1949, only a rough estimate of one-eighth
of the digitized holdings are indexed in folders and accessible here. Many
small and large commodities/wares such as China, India, France or the USA are
missing at all or are only represented by a few folders originating from the
"Forschungsstelle für das Übersee-Deutschtum".

All unprocessed material is accessible under [digitized
films](/film/h1_wa.de.html) (in German), including material from the [second
filming (until 1960)](/film/h2_wa.de.html) - for copyright reasons, however,
unfortunately only in the ZBW reading room. The [complete ware category
system](https://pm20.zbw.eu/report/vocab/ware_by_signature.en.html) is
available online.
</tmpl_if>

